// Wyjątki

try {
    // throw new Error('Napotkałem problem!');
    console.log('Wszystko w porządku');
} catch (err) {
    console.error(err);
}